#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# @description      clusterctl - Kubernetes cluster friendly CLI utility
#
# @author           Andrea Benini
# @date             2024-11-20
# @license          GNU Affero General Public License v3.0
# @see              CLI utility for managing local kubernetes installation
#
# pyright: reportMissingImports=false
#
VERSION='0.1.1'
CODENAME='Attila'

import os
import sys
try:
    import yaml
    import stat
    import requests
    import argparse
    import subprocess
    from   clusterops.system     import System
    from   clusterops.kubernetes import Kubernetes
except Exception as E:
    print(f"Error while importing modules:\n{str(E)}\nAborting program\n\n")
    sys.exit(1)


class clusterController(object):
    def __init__(self, config=None, command=None, kubernetes=None, osType=None):
        try:
            # Loading default configuration
            print(f"\n[Loading Setup]")
            print(f"- Detecting current kubernetes configuration (--dry-run {System.dryrun})")
            print(f"- Loading configuration file {config} ...")
            self.config = System.LoadYAML(config)
            self.config.setdefault("metadata", {})
            self.config["metadata"].setdefault("uninstall", "none")
            self.config["metadata"].setdefault("name", "default")
            self.config.setdefault("spec", {})
            self.config["spec"].setdefault("addons", {})
            print(f"- Kubernetes engine: {kubernetes}")
            print(f"- Operating system: {osType}")
            self.kubernetes = Kubernetes(engine=kubernetes, osType=osType)
            # Execute the desired command
            if command == 'install':
                self.install()
            elif command == 'remove':
                self.remove()
            else:
                raise Exception(f"Invalid command: {command}")
        except KeyboardInterrupt:
            System.Exit(exit=0, Prepend='')
        except Exception as E:
            System.Exit(str(E))

    def __ExecFunction(self, methodName):
        method = System.MethodName(object=self.kubernetes, method=methodName)
        if method:
            method(self.config)
        else:
            System.Exit(f"method '{methodName}()' unsupported at the moment")

    # Optional components, mostly based on config.yml
    def __ComponentsLoop(self):
        for item in self.config['spec']['addons']:
            if type(item) == str:
                yield item
            elif type(item) == dict and len(item)>0:
                yield list(item)[0]
            else:
                yield None


    def install(self):
        if not System.Confirm(f"\nThis script will configure {self.kubernetes.engine} for your '{self.kubernetes.os} OS'\nUse --dry-run flag for a preview of what it does\n\nDo you really want to continue [y|N] ? "):
            System.Exit(exit=0, Prepend='')
        # Mandatory installation components, if any
        self.__ExecFunction(f"install_{self.kubernetes.os}_{self.kubernetes.engine}")
        for componentName in self.__ComponentsLoop():
            if componentName == 'kubevirt':
                self.kubernetes.install_KubernetesKubeVirt()
            elif componentName == 'containerhub':
                self.kubernetes.install_clusteropsService()
            else:
                System.Exit(f"- Component '{componentName}' is not actually supported")
        System.Line(title="Installation Completed")


    def remove(self):
        if self.config['metadata']['uninstall'] == 'none':
            System.Exit(Message="Disinstallation not required, 'uninstall' has been set to 'none' in the config file", Prepend='', exit=0)
        print(f"\nRemoving kubernetes configuration, parameter 'uninstall' set to '{self.config['metadata']['uninstall']}', this will:")
        if self.config['metadata']['uninstall'] in ('config', 'all'):
            print(f'    - remove personal configuration "{self.kubernetes.homeConfigFile}" and local "{self.kubernetes.engine}" configuration files')
            print(f'    - remove ContainerHub service daemon')
            print(f'    - remove kubernetes plugins and traefik controller')
            print(f'    - drain the node by deleting all containers and configs')
        if self.config['metadata']['uninstall'] in ('binaries', 'all'):
            print(f'    - uninstall {self.kubernetes.engine} package from {self.kubernetes.os}')
        if not System.Confirm(f"\nDo you really want to continue [y|N] ? "):
            System.Exit(exit=0, Prepend='')
        print()
        # Remove system containers and base configuration
        if self.config['metadata']['uninstall'] in ('config', 'all'):
            for componentName in self.__ComponentsLoop():
                if componentName == 'kubevirt':
                    self.kubernetes.remove_KubernetesKubeVirt()
                elif componentName == 'containerhub':
                    self.kubernetes.remove_clusteropsService()
                else:
                    System.Exit(f"- Component '{componentName}' is not actually supported")
            self.kubernetes.remove_drainKubernetes()
            self.__ExecFunction(f"remove_{self.kubernetes.os}_{self.kubernetes.engine}_configuration")

        # Remove binaries and installation
        if self.config['metadata']['uninstall'] in ('binaries', 'all'):
            self.__ExecFunction(f"remove_{self.kubernetes.os}_{self.kubernetes.engine}_binaries")
        print(f"--> File {self.kubernetes.homeConfigFile} and its directory have been left intact")
        print(f"    Remove them on your own if you don't need it anymore")
        System.Line(title="Installation Removed")


def main():                             # Entry point for the package (when installed from pip)
    System.ForbidRootExecution()
    configFile = System.configPath + os.path.sep + 'config.yml'
    parser = argparse.ArgumentParser(description='Kubernetes cluster friendly CLI utility', epilog=System.epilogInfoTxt, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('-o', '--os',         dest='ostype',     required=True, choices=['arch','suse'], help=f"Underlying operating system: [arch|suse]")
    parser.add_argument('-k', '--kubernetes', dest='kubernetes', default="k3s", choices=['k3s'],  help=f"Kubernetes orchestration engine [default: k3s]")
    parser.add_argument('-c', '--config',     dest='config',     default=configFile, help=f"Cluster configuration file   [default: {os.path.basename(configFile)}]")
    parser.add_argument('-d', '--dry-run', action='store_true',  help="Perform a trial run, no changes made")
    parser.add_argument("command", choices=["install","remove"], help="The command to execute.")
    argument = parser.parse_args()
    System.dryrun = argument.dry_run
    clusterController(config=argument.config, command=argument.command, kubernetes=argument.kubernetes, osType=argument.ostype)
if __name__ == "__main__":
    main()
