apiVersion: app.my.domain/v1alpha1
kind: ClusterConfig
metadata:
  labels:
    app.kubernetes.io/name: src

  # Kubernetes cluster name
  name: localCluster

  # uninstall method
  #     all       - Remove everything: system configs, binary package
  #     config    - Uninstall system containers and kubernetes configs
  #     binaries  - Uninstall binary installation packages [ONLY], through package manager
  #     none      - Do nothing, do not uninstall (default)
  uninstall: all

spec:
  # Kubernetes configuration addons
  addons:
    - dashboard:            # Install latest kubernetes dashboard (CNCF default)
        url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
    - kubevirt              # Add Kubevirt virtualization capabilities
