apiVersion: clusterops.io/v1alpha1
kind: ClusterConfig
metadata:
  name: myCluster
  # uninstall method
  #     all       - Remove everything: containers, configs, binary package
  #     container - Uninstall containers
  #     config    - Uninstall containers AND kubernetes configs
  #     binaries  - Uninstall binary installation package ONLY through package manager
  #     none      - Do nothing, do not uninstall (default)
  uninstall: all
spec:
#  network:
#    plugin: calico
#  storage:
#    provider: longhorn
  addons:
    - metrics-server
    - dashboard
    # - ingress-nginx
